### ISSUE TITLE
Enregistrer n'enregistre pas le nouvel animal

### ISSUE THREAD

**Issue by Prakkkmak** [Prakkkmak/animaliste-front#13]
Lorsque je créer un nouvel animal et que j'appuie sur "enregistrer" l'animal en se créer pas et rien ne se passe

**Comment by Prakkkmak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enregistrer n'enregistre pas le nouvel animal](https://trello.com/c/DWNo3dK0/73-enregistrer-nenregistre-pas-le-nouvel-animal)

**Comment by BastienLamour** [comment]
Le problème venait du Back.
Création d'une issue dans le back avec le lien vers celle-ci.
https://github.com/Prakkkmak/animaliste-back/issues/9

Problème résolu.

**Comment by Prakkkmak** [comment]
Parfait, à avoir quand il y aura la gestion des erreurs
