### ISSUE TITLE
Mauvaise suppression dans le tableau

### ISSUE THREAD

**Issue by BastienLamour** [Prakkkmak/animaliste-front#25]
Lors de la suppression d'un animal, c'est le dernier élément du tableau qui est supprimer et non pas celui voulu.
La suppression se fait normalement dans la base.

**Comment by BastienLamour** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Problème lors de la suppression d'un animal.](https://trello.com/c/OfgITrcM/103-probl%C3%A8me-lors-de-la-suppression-dun-animal)

**Comment by Prakkkmak** [comment]
Résolu
