### ISSUE TITLE
Erreur lors de la création d'un compte.

### ISSUE THREAD

**Issue by BastienLamour** [Prakkkmak/animaliste-front#26]
Lors de la création d'un compte, le serveur renvoie la réponse 400.

**Comment by BastienLamour** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Problème lors de la création d'un compte.](https://trello.com/c/IWd9W0Yr/104-probl%C3%A8me-lors-de-la-cr%C3%A9ation-dun-compte)

**Comment by Prakkkmak** [comment]
Résolu
