### ISSUE TITLE
Mauvais enregistrement de la valeur du sex d'un animal

### ISSUE THREAD

**Issue by BastienLamour** [Prakkkmak/animaliste-front#27]
Lors de l'enregistrement, le sex de l'animal ne prend une mauvais valeur ou ne prend pas de valeur.

**Comment by BastienLamour** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mauvaise données enregistrée pour le sexe de l'animal](https://trello.com/c/cGPQ8KNP/106-mauvaise-donn%C3%A9es-enregistr%C3%A9e-pour-le-sexe-de-lanimal)

**Comment by Prakkkmak** [comment]
Resolved
